version: '3'
services:
  my-app:
    image: jasonhoe928/demo-website:${IMAGE_VERSION}-local
    command: ["./node_modules/.bin/nodemon", "app.js"]
    container_name: ap-express
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "5000:${PORT}"
    networks:
      - my-app-network

networks:
  my-app-network: